name: Build and Push Docker Image (Simple)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: linux-x86
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Codeberg
        run: |
          echo "${{ secrets.REPO_TOKEN }}" | docker login codeberg.org -u "${{ github.actor }}" --password-stdin

      - name: Build and push
        run: |
          docker build -t codeberg.org/${{ github.repository_owner }}/pdfconvertorbot:${{ github.ref_name }} .
          docker push codeberg.org/${{ github.repository_owner }}/pdfconvertorbot:${{ github.ref_name }}

      - name: Push latest tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker tag codeberg.org/${{ github.repository_owner }}/pdfconvertorbot:${{ github.ref_name }} codeberg.org/${{ github.repository_owner }}/pdfconvertorbot:latest
          docker push codeberg.org/${{ github.repository_owner }}/pdfconvertorbot:latest
